# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "3.7"

volumes:
  WDRAOrg.orderer.com:
  peer0.BankOrg.example.com:
  peer0.CollateralManagersOrg.example.com:
  peer0.InsuranceOrg.example.com:
  peer0.TransportOrg.example.com:
  peer0.WareHouseOrg.example.com:

networks:
  WDRA:
    name: WDRA

services:

  WDRAOrg.orderer.com:
    container_name: WDRAOrg.orderer.com
    image: hyperledger/fabric-orderer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=WDRAOrg
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
      - ORDERER_OPERATIONS_LISTENADDRESS=WDRAOrg.orderer.com:9443
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: orderer
    volumes:
      - ./organizations/ordererOrganizations/WDRAOrg.orderer.com/orderers/orderer.WDRAOrg.orderer.com/msp:/var/hyperledger/orderer/msp
      - ./organizations/ordererOrganizations/WDRAOrg.orderer.com/orderers/orderer.WDRAOrg.orderer.com/tls/:/var/hyperledger/orderer/tls
      - WDRAOrg.orderer.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
      - 7053:7053
      - 9443:9443
    networks:
      - WDRA

  peer0.BankOrg.example.com:
    container_name: peer0.BankOrg.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.BankOrg.example.com
      - CORE_PEER_ADDRESS=peer0.BankOrg.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.BankOrg.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.BankOrg.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.BankOrg.example.com:7051
      - CORE_PEER_LOCALMSPID=BankOrgMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.BankOrg.example.com:9444
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0BankOrg"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - ./organizations/peerOrganizations/BankOrg.example.com/peers/peer0.BankOrg.example.com:/etc/hyperledger/fabric
      - peer0.BankOrg.example.com:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 7051:7051
      - 9444:9444
    networks:
      - WDRA

  peer0.CollateralManagersOrg.example.com:
    container_name: peer0.CollateralManagersOrg.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.CollateralManagersOrg.example.com
      - CORE_PEER_ADDRESS=peer0.CollateralManagersOrg.example.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.CollateralManagersOrg.example.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.CollateralManagersOrg.example.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.CollateralManagersOrg.example.com:9051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.CollateralManagersOrg.example.com:9445
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0CollateralManagerOrg"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - ../organizations/peerOrganizations/org2.example.com/peers/peer0.CollateralManagersOrg.example.com:/etc/hyperledger/fabric
      - peer0.CollateralManagersOrg.example.com:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 9051:9051
      - 9445:9445
    networks:
      - WDRA

  peer0.InsuranceOrg.example.com:
    container_name: peer0.InsuranceOrg.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.InsuranceOrg.example.com
      - CORE_PEER_ADDRESS=peer0.InsuranceOrg.example.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.InsuranceOrg.example.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.InsuranceOrg.example.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.InsuranceOrg.example.com:8051
      - CORE_PEER_LOCALMSPID=InsuranceOrgMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.InsuranceOrg.example.com:9446
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0InsuranceOrg"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - ./organizations/peerOrganizations/InsuranceOrg.example.com/peers/peer0.InsuranceOrg.example.com:/etc/hyperledger/fabric
      - peer0.InsuranceOrg.example.com:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 8051:8051
      - 9446:9446
    networks:
      - WDRA

  peer0.TransportOrg.example.com:
    container_name: peer0.TransportOrg.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.TransportOrg.example.com
      - CORE_PEER_ADDRESS=peer0.TransportOrg.example.com:8151
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8151
      - CORE_PEER_CHAINCODEADDRESS=peer0.TransportOrg.example.com:8152
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8152
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.TransportOrg.example.com:8151
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.TransportOrg.example.com:8151
      - CORE_PEER_LOCALMSPID=TransportOrgMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.TransportOrg.example.com:9447
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0TransportOrg"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - ../organizations/peerOrganizations/TransportOrg.example.com/peers/peer0.TransportOrg.example.com:/etc/hyperledger/fabric
      - peer0.TransportOrg.example.com:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 8151:8151
      - 9447:9447
    networks:
      - WDRA
  
  peer0.WareHouseOrg.example.com:
    container_name: peer0.WareHouseOrg.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.WareHouseOrg.example.com
      - CORE_PEER_ADDRESS=peer0.WareHouseOrg.example.com:8251
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8251
      - CORE_PEER_CHAINCODEADDRESS=peer0.WareHouseOrg.example.com:8252
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8252
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.WareHouseOrg.example.com:8251
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.WareHouseOrg.example.com:8251
      - CORE_PEER_LOCALMSPID=WareHouseOrgMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.WareHouseOrg.example.com:9448
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0WareHouseOrg"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - ../organizations/peerOrganizations/WareHouseOrg.example.com/peers/peer0.WareHouseOrg.example.com:/etc/hyperledger/fabric
      - peer0.WareHouseOrg.example.com:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 8251:8251
      - 9448:9448
    networks:
      - WDRA

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    labels:
      service: hyperledger-fabric
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - FABRIC_LOGGING_SPEC=INFO
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
    #- FABRIC_LOGGING_SPEC=DEBUG
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - ../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
      - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
    depends_on:
      - peer0.BankOrg.example.com
      - peer0.CollateralManagersOrg.example.com
      - peer0.InsuranceOrg.example.com
      - peer0.TransportOrg.example.com
      - peer0.WareHouseOrg.example.com
    networks:
      - WDRA
